app_name: portfolio-www-test
app_namespace: test
app_folder: apps/portfolio-www-test/
app_domains:
  - test4849.oberpierre.com
container_image: "{{ lookup('ansible.builtin.env', 'CONTAINER_IMAGE') }}"
container_port: 80
registry:
  host: ghcr.io
  username: oberpierre
  password: "{{ lookup('ansible.builtin.env', 'REGISTRY_PASSWORD') }}"
